builder:
  build: ./
  stdin_open: true
  tty: true
  dockerfile: docker/Dockerfile.builder
  links:
    - ganache
  environment:
    SET_CONTAINER_TIMEZONE: 'True'
    CONTAINER_TIMEZONE: Europe/Prague
  volumes:
    - "./build/original:/marblegame/original/build"
    - "./build/bank:/marblegame/bank/build"
    - "./build/metatransactions:/marblegame/metatransactions/build"
    - "./src/original/contracts:/marblegame/original/contracts"
    - "./src/original/migrations:/marblegame/original/migrations"
    - "./src/original/test:/marblegame/original/test"
    - "./src/original/deployments:/marblegame/original/deployments"
    - "./src/bank/contracts:/marblegame/bank/contracts"
    - "./src/bank/migrations:/marblegame/bank/migrations"
    - "./src/bank/test:/marblegame/bank/test"
    - "./src/metatransactions/contracts:/marblegame/metatransactions/contracts"
    - "./src/metatransactions/migrations:/marblegame/metatransactions/migrations"
    - "./src/metatransactions/test:/marblegame/metatransactions/test"

ganache:
  image: trufflesuite/ganache-cli:latest
  command: ganache -p 8545 -h 0.0.0.0 --mnemonic "${mnemonic}"
  environment:
    SET_CONTAINER_TIMEZONE: 'True'
    CONTAINER_TIMEZONE: Europe/Prague
