builder:
  build: ./
  stdin_open: true
  tty: true
  dockerfile: docker/Dockerfile.builder
  links:
    - ganache
  environment:
    SET_CONTAINER_TIMEZONE: 'True'
    CONTAINER_TIMEZONE: Europe/Prague
  volumes:
    - "./build/core:/marblegame/core/build"
    - "./build/metatransactions:/marblegame/metatransactions/build"
    - "./src/core/contracts:/marblegame/core/contracts"
    - "./src/core/migrations:/marblegame/core/migrations"
    - "./src/core/test:/marblegame/core/test"
    - "./src/core/deployments:/marblegame/core/deployments"
    - "./src/metatransactions/contracts:/marblegame/metatransactions/contracts"
    - "./src/metatransactions/migrations:/marblegame/metatransactions/migrations"
    - "./src/metatransactions/test:/marblegame/metatransactions/test"
    - "./src/metatransactions/deployments:/marblegame/metatransactions/deployments"

ganache:
  image: trufflesuite/ganache-cli:latest
  command: ganache -p 8545 -h 0.0.0.0 --mnemonic "${mnemonic}" --blockTime 5
  environment:
    SET_CONTAINER_TIMEZONE: 'True'
    CONTAINER_TIMEZONE: Europe/Prague
